_wandb:
    value:
        cli_version: 0.21.3
        e:
            vji11d0xooddultvelz3sk69yjcdtjdp:
                args:
                    - --resume
                    - checkpoints/lagos2duplex/latest.pt
                    - --config
                    - configs/lagos2duplex_tune.json
                cpu_count: 2
                cpu_count_logical: 4
                disk:
                    /:
                        total: "250551357440"
                        used: "219426418688"
                email: theelvace@gmail.com
                executable: /Users/mac/Lagos-GAN/.venv/bin/python3
                git:
                    commit: 78a5b3bc4c173bc5c937270aee50ee01cf845a09
                    remote: https://github.com/Elvaceishim/Lagos-GAN-clean.git
                host: elvis
                memory:
                    total: "17179869184"
                os: macOS-13.7.8-x86_64-i386-64bit
                program: -m lagos2duplex.train
                python: CPython 3.9.6
                root: /Users/mac/Lagos-GAN
                startedAt: "2025-09-16T15:30:29.826123Z"
                writerId: vji11d0xooddultvelz3sk69yjcdtjdp
        m: []
        python_version: 3.9.6
        t:
            "1":
                - 1
                - 41
                - 49
                - 80
                - 105
            "2":
                - 1
                - 41
                - 49
                - 80
                - 105
            "3":
                - 16
                - 61
            "4": 3.9.6
            "5": 0.21.3
            "12": 0.21.3
            "13": darwin-x86_64
data:
    value:
        augmentations: true
        data_path: data_processed
        image_size: 256
        num_workers: 4
        paired: false
        pin_memory: true
logging:
    value:
        display_freq: 400
        eval_fid_freq: 10
        num_test_samples: 4
        print_freq: 100
        save_epoch_freq: 20
        save_latest_freq: 5000
        use_tensorboard: false
        use_wandb: true
        wandb_project: lagosgan-lagos2duplex
        wandb_run_name: null
model:
    value:
        init_gain: 0.02
        init_type: normal
        input_nc: 3
        n_layers_D: 3
        ndf: 64
        netD: basic
        netG: resnet_9blocks
        ngf: 64
        norm: instance
        output_nc: 3
        use_dropout: false
paths:
    value:
        checkpoints_dir: ./checkpoints/lagos2duplex
        logs_dir: /Users/mac/Lagos-GAN/logs/lagos2duplex
        project_root: /Users/mac/Lagos-GAN
        results_dir: /Users/mac/Lagos-GAN/results/lagos2duplex
        resume_checkpoint: checkpoints/lagos2duplex/latest.pt
system:
    value:
        compile_model: false
        deterministic: false
        device: cpu
        gpu_ids: null
        mixed_precision: false
        seed: 42
training:
    value:
        batch_size: 1
        beta1: 0.5
        beta2: 0.999
        cycle_loss_type: l1
        gan_mode: lsgan
        identity_loss_type: l1
        lambda_cycle: 10
        lambda_identity: 0.5
        lambda_perceptual: 0.1
        learning_rate: 0.0002
        lr_decay_iters: 50
        lr_policy: linear
        max_grad_norm: null
        n_epochs_decay: 100
        num_epochs: 200
        pool_size: 50
