name: CI & Publish

on:
  push:
    branches: [main, master]
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.inference.txt
          pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest -q

  build-and-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.prod
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/lagos-gan-inference:latest
            ghcr.io/${{ github.repository_owner }}/lagos-gan-inference:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
