name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dev requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.inference.txt
          pip install -r requirements-dev.txt
      - name: Run tests
        run: pytest -q

  build-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.prod
          push: false
          tags: lagos-gan-inference:ci
