name: Sync Space
on:
  push:
    branches: [main]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install HF CLI
        run: pip install --upgrade huggingface_hub[cli]

      - name: Sync selected files to Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: ${{ secrets.HF_SPACE }}
        run: |
          huggingface-cli upload --repo-type space --repo-id "$HF_SPACE" --token "$HF_TOKEN" --path demo --destination demo
          huggingface-cli upload --repo-type space --repo-id "$HF_SPACE" --token "$HF_TOKEN" --path README.md --destination README.md
          huggingface-cli upload --repo-type space --repo-id "$HF_SPACE" --token "$HF_TOKEN" --path requirements.txt --destination requirements.txt
          huggingface-cli upload --repo-type space --repo-id "$HF_SPACE" --token "$HF_TOKEN" --path requirements.inference.txt --destination requirements.inference.txt
          huggingface-cli upload --repo-type space --repo-id "$HF_SPACE" --token "$HF_TOKEN" --path models --destination models
